const {readFileSync}=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const groupId='00000000-0000-4000-8000-000000000000'+'.'+'b'.repeat(64),token='a'.repeat(64);
const elements=new Map(),stored=new Map(),requests=[];
const element=()=>({value:'',hidden:false,disabled:false,type:'password',textContent:'',children:[],replaceChildren(...children){this.children=children;},append(...children){this.children.push(...children);},setAttribute(){},focus(){},select(){}});
const $=id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id);};
let role='owner',copied='';
const context={$,console,clone:structuredClone,location:{hostname:'ctrlcctrlvisthebest.github.io',protocol:'https:',origin:'https://ctrlcctrlvisthebest.github.io',pathname:'/bilingual-subtitle-editor/',search:'',hash:''},URL,URLSearchParams,AbortController,setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,localStorage:{getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v)},navigator:{clipboard:{async writeText(value){copied=value;}}},document:{createElement:element,addEventListener(){}},window:{addEventListener(){},history:{replaceState(){}}},ready:Promise.resolve(),draw(){},persist(){},project:{editor_id:'blank',rows:[],appearance:{mode:'outline'}},idx:0};
context.fetch=async(url,options)=>{
 requests.push({url,options});
 const data=options.method==='POST'?{groupId,token,member:{id:'owner-id',name:'测试组长',role:'owner'},groupName:'虚拟测试组'}:{groupName:'虚拟测试组',member:{id:'owner-id',name:'测试组长',role},members:[{id:'owner-id',name:'测试组长',role,last_seen:Date.now()}],projects:[]};
 return {ok:true,json:async()=>data};
};
vm.createContext(context);
vm.runInContext(readFileSync(__dirname+'/collaboration-core.js','utf8'),context);
vm.runInContext(readFileSync(__dirname+'/collaboration.js','utf8'),context);
(async()=>{
 await Promise.resolve();
 $('cloudNewName').value='虚拟测试组';$('cloudNickname').value='测试组长';
 await $('cloudCreate').onclick();
 const creation=requests.find(r=>r.options.method==='POST');
 assert(creation.url.startsWith('https://bilingual-subtitle-editor.zoeli2010xl.workers.dev/'));
 assert.deepEqual(JSON.parse(creation.options.body),{name:'虚拟测试组',memberName:'测试组长'});
 assert.equal($('cloudCreate').disabled,false);
 const key=$('cloudOwnerKey').value;assert.equal(key,'sg1_'+groupId+'.'+token);assert.equal($('cloudOwnerKey').type,'password');assert.equal($('cloudLeaderTools').hidden,false);
 await $('cloudCopyLeaderKey').onclick();assert.equal(copied,key);
 await $('cloudDisconnect').onclick();assert.equal($('cloudOwnerKey').value,'');
 $('cloudLeaderLogin').value=key;requests.length=0;
 await $('cloudLeaderConnect').onclick();
 assert(requests.every(r=>r.options.method==='GET'));
 assert.equal(requests[0].options.headers.Authorization,'Bearer '+token);
 assert.equal($('cloudLeaderLogin').value,'');assert.equal($('cloudOwnerKey').value,key);
 assert.equal(vm.runInContext('cloud.session.member.role',context),'owner');
 await $('cloudDisconnect').onclick();role='viewer';$('cloudLeaderLogin').value=key;
 await $('cloudLeaderConnect').onclick();
 assert.equal(vm.runInContext('cloud.session',context),null);
 assert($('cloudStatus').textContent.includes('不是组长密钥'));assert.equal($('cloudOwnerKey').value,'');
 role='owner';context.location.hash='#subtitleGroup='+groupId+'&backend=https%3A%2F%2Funtrusted.example&invite=invalid';
 vm.runInContext('cloudInit()',context);assert($('cloudStatus').textContent.includes('不属于当前字幕网站'));
 vm.runInContext("cloud.server='https://untrusted.example'",context);requests.length=0;$('cloudLeaderLogin').value=key;
 await $('cloudLeaderConnect').onclick();assert(requests.length);assert(requests.every(r=>r.url.startsWith('https://bilingual-subtitle-editor.zoeli2010xl.workers.dev/')));
 assert(!JSON.stringify(context.project).includes(token));
 console.log('通过：直接建组无需全站密钥、复制专属密钥、粘贴只读恢复组长身份、拒绝普通成员冒充组长、不向其他网站发送组长凭证、工程不含登录凭证。');
})().catch(error=>{console.error(error);process.exitCode=1;});
