const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context={clone:v=>structuredClone(v)};vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/collaboration-core.js','utf8'),context);
const call=(name,...args)=>{context.args=args;return JSON.parse(JSON.stringify(vm.runInContext(name+'(...args)',context)));};
const row=id=>({id,start:1,end:2,zh:id,en:id,speaker:'Unknown',status:'疑点待听校',note:''});
const p={version:1,editor_id:'shared-test',title:'工程',colors:{Unknown:'#455a64'},rows:[row('a'),row('b')]};
const base={project:p,rowVersions:{a:1,b:1},metaVersion:1,orderVersion:1,revision:1};
const local=structuredClone(p),remote=structuredClone(p);local.rows[0].zh='我的修订';remote.rows[1].en='Other member';
let merged=call('collabMerge',p,local,remote);assert.equal(merged.conflicts.length,0);assert.equal(merged.project.rows[0].zh,'我的修订');assert.equal(merged.project.rows[1].en,'Other member');
let patch=call('collabPatch',base,local);assert.equal(patch.changes.length,1);assert.equal(patch.changes[0].expected,1);assert(!patch.order);
remote.rows[0].zh='其他人的修订';merged=call('collabMerge',p,local,remote);assert.equal(merged.conflicts[0].kind,'row');assert.equal(merged.project.rows[0].zh,'我的修订');assert.equal(merged.conflicts[0].remote.zh,'其他人的修订');
const deletion=structuredClone(p);deletion.rows.shift();merged=call('collabMerge',p,deletion,remote);assert(merged.conflicts.some(c=>c.kind==='row'&&c.id==='a'));assert.equal(merged.conflicts.find(c=>c.id==='a').local,null);
const otherAdd=structuredClone(p),mineAdd=structuredClone(p);otherAdd.rows.push(row('r'));mineAdd.rows.push(row('l'));merged=call('collabMerge',p,mineAdd,otherAdd);assert(merged.conflicts.some(c=>c.kind==='order'));assert.deepEqual(new Set(merged.project.rows.map(r=>r.id)),new Set(['a','b','l','r']));
const restored=structuredClone(p);restored.rows.push(row('toString'));patch=call('collabPatch',base,restored);assert.equal(patch.changes[0].expected,0);assert(patch.order);
const meta=structuredClone(p);meta.title='新标题';patch=call('collabPatch',base,meta);assert.equal(patch.meta.expected,1);assert.equal(patch.changes.length,0);
assert.equal(call('collabDirty',base,p),false);
const groupId='00000000-0000-4000-8000-000000000000'+'.'+'b'.repeat(64),token='a'.repeat(64);
const leaderKey=call('collabLeaderKey',groupId,token);
assert.deepEqual(call('collabParseLeaderKey',' \n'+leaderKey+'\n '),{groupId,token});
for(const invalid of ['',token,leaderKey.slice(0,-1),leaderKey+'.extra',leaderKey.replace('sg1_','wr1_')])assert.throws(()=>call('collabParseLeaderKey',invalid));
assert.throws(()=>call('collabLeaderKey','bad-group',token));
assert.throws(()=>call('collabLeaderKey',groupId,'bad-token'));
assert(!JSON.stringify(p).includes(token));
console.log('通过：不同字幕同时编辑自动合并；相同字幕、删除和顺序冲突保留双方内容；逐条版本与原型键保护。');
console.log('通过：组长密钥完整恢复及无效、截断、混用格式拒绝。');
